databases:
  - name: todo_apidb
    plan: free
    databaseName: todo_api
    user: todo_api

services:
  - type: web
    plan: free
    name: todo_api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn todo_api.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo_apidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
