# Generated by Django 5.0.6 on 2024-06-05 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blogpost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='id',
            new_name='post_id',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
